# boolean을 활용한 numpy 필터링

In [1]:
import numpy as np

In [3]:
array1 = np.array([1, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
array1

array([ 1,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [4]:
array1 > 4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [5]:
array1 % 2 == 0

array([False, False, False, False, False, False, False, False, False,
       False, False])

### boolean값이 있는 numpy array 만들기

In [6]:
# boolean값이 있는 numpy array 만들기
booleans = np.array([True, True, False, True, True, False, True, True, True, False, True])

### where : True가 있는 값의 인덱스를 가져오기

In [7]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [9]:
filter = np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

### 특정 조건을 만족하는 값만 가져오기

In [10]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

# 실습과제 

영훈이가 창업한 흥부부대찌개 신주쿠점은 이제 직장인들에게 소문난 맛집입니다. 그러나 매일같이 성공적인 것은 아닙니다. 목표 일 매출을 달성하지 못하는 날들이 아직 꽤 있거든요. 영훈이가 생각하는 성공적인 하루 매출은 20만 엔입니다.

성공적이지 않은 날의 매출만 골라서 보고 싶습니다. 20만 엔 이하의 매출만 담긴 numpy array를 출력해주세요.
반복문은 사용하면 안 됩니다!

주의: 정답 출력 코드는 print 없이 작성해 주세요. (예시: bad_days_revenue)

In [11]:
import numpy as np

revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
bad_days_revenue = np.array(revenue_in_yen)
fit = np.where(bad_days_revenue < 200000)
# 정답 출력
bad_days_revenue[fit]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])