# **파이썬 리스트를 통해 생성**

**`numpy`** 모듈의 **`array`** 메소드에 파라미터로 파이썬 리스트를 넘겨주면 numpy array가 리턴됩니다.

```
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

print(array1)

```

```
[ 2  3  5  7 11 13 17 19 23 29 31]

```

# **균일한 값으로 생성**

**`numpy`** 모듈의 **`full`** 메소드를 사용하면, 모든 값이 같은 numpy array를 생성할 수 있습니다.

```
array1 = numpy.full(6, 7)

print(array1)

```

```
[7 7 7 7 7 7]

```

## **모든 값이 0인 numpy array 생성**

모든 값이 **`0`**인 numpy array를 생성하기 위해서는 **`full`** 메소드를 사용하면 되겠죠. 하지만 사실은 더 간편한 방법이 있습니다.

```
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype=int)

print(array1)
print()
print(array2)

```

```
[0 0 0 0 0 0]

[0 0 0 0 0 0]

```

## **모든 값이 1인 numpy array 생성**

모든 값이 **`1`**인 numpy array를 생성하는 것도 비슷합니다. **`zeros`** 메소드 대신 **`ones`**를 사용하면 됩니다.

```
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype=int)

print(array1)
print()
print(array2)

```

```
[1 1 1 1 1 1]

[1 1 1 1 1 1]

```

# **랜덤한 값들로 생성**

어쩔 때는 임의의 값들로 배열을 생성시키고 싶습니다. 그럴 때는 **`numpy`**의 **`random`** 모듈의 **`random`** 함수를 사용하면 됩니다.

**`numpy`** 모듈 안에 **`random`**이라는 모듈이 있고, 그 안에 또 **`random`**이라는 함수가 있는 겁니다!

```
array1 = numpy.random.random(6)
array2 = numpy.random.random(6)

print(array1)
print()
print(array2)

```

```
[0.42214929 0.45275673 0.57978413 0.61417065 0.39448558 0.03347601]

[0.42521953 0.65091589 0.94045742 0.18138103 0.27150749 0.8450694 ]

```

# **연속된 값들이 담긴 numpy array 생성**

**`numpy`** 모듈의 **`arange`** 함수를 사용하면 연속된 값들이 담겨 있는 numpy array를 생성할 수 있습니다.

**`arange`** 함수는 파이썬의 기본 함수인 **`range`**와 굉장히 비슷한 원리로 동작하는데요. 파라미터가 1개인 경우, 2개인 경우, 3개인 경우 모두 살펴봅시다.

## **파라미터 1개**

**`arange(m)`**을 하면 **`0`**부터 **`m-1`**까지의 값들이 담긴 numpy array가 리턴됩니다.

```
array1 = numpy.arange(6)
print(array1)

```

```
[0 1 2 3 4 5]

```

## **파라미터 2개**

**`arange(n, m)`**을 하면 **`n`**부터 **`m-1`**까지의 값들이 담긴 numpy array가 리턴됩니다.

```
array1 = numpy.arange(2, 7)
print(array1)

```

```
[2 3 4 5 6]

```

## **파라미터 3개**

**`arange(n, m, s)`**를 하면 **`n`**부터 **`m-1`**까지의 값들 중 간격이 **`s`**인 값들이 담긴 numpy array가 리턴됩니다.

```
array1 = numpy.arange(3, 17, 3)
print(array1)

```

```
[ 3  6  9 12 15]
```

## numpy 생성 연습 1

### 실습과제
1부터 100까지(1과 100 포함) 담겨 있는 numpy array를 생성하고 출력해 주세요.

주의:정답 출력 코드는 print(arr)이 아닌 arr로 작성해 주세요.

In [2]:
import numpy as np
arr = np.arange(1, 101)
# 코드를 작성하세요.

# 정답 출력
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

## numpy 생성 연습 2

### 실습과제
1부터 100까지(1과 100 포함) 중 3의 배수만 담겨 있는 numpy array를 생성하고 출력해 주세요.

주의: 정답 출력 코드는 print(arr)이 아닌 arr로 작성해 주세요.

In [3]:
import numpy as np
arr = np.arange(3, 101, 3)
# 코드를 작성하세요.

# 정답 출력
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## numpy 기본 연산
numpy는 수치계산을 위한 파이썬 도구이다.



In [5]:
import numpy as np 
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [6]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
# 곱하기, 나누기, 더하기, 제곱
array1 * 2
array1 / 2
array1 + 2
array1 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [12]:
# array값이 변하게 하고 싶으면 변수에 다시 저장
array1 = array1 * 2
array1

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [13]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [14]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
# array끼리 연산 가능
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])